# Generated by Django 4.0.3 on 2022-03-08 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Dhaka Metro', 'Dhaka Metro'), ('Dhaka Mirpur 10', 'Dhaka Mirpur 10'), ('Dhaka Gulshan', 'Dhaka Gulshan'), ('Dhaka Mirpur 12', 'Dhaka Mirpur 12'), ('Sylhet', 'Sylhet'), ('Kanaigat', 'Kanaigat'), ('Beanibazar', 'Beanibazar'), ('Golapgonj', 'Golapgonj'), ('Jkoigonj', 'Joigonj')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('specialist', models.CharField(blank=True, max_length=200)),
                ('chamber', models.CharField(max_length=300)),
                ('chamber_address', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('visiting_hour', models.CharField(max_length=200)),
                ('new_patient_fee', models.IntegerField(blank=True, null=True)),
                ('old_patient_fee', models.IntegerField(blank=True, null=True)),
                ('report_checking_fee', models.IntegerField(blank=True, null=True)),
                ('doctor_img', models.ImageField(blank=True, null=True, upload_to='doctorimg')),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Dhaka Metro', 'Dhaka Metro'), ('Dhaka Mirpur 10', 'Dhaka Mirpur 10'), ('Dhaka Gulshan', 'Dhaka Gulshan'), ('Dhaka Mirpur 12', 'Dhaka Mirpur 12'), ('Sylhet', 'Sylhet'), ('Kanaigat', 'Kanaigat'), ('Beanibazar', 'Beanibazar'), ('Golapgonj', 'Golapgonj'), ('Jkoigonj', 'Joigonj')], default='Dhaka', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cattype', models.CharField(default='Tablet', max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('Disclaimer', models.TextField(default='no')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('C', 'Covid 19 Special'), ('D', 'Devices'), ('H', 'Herbal and Homeopathy'), ('BM', 'Baby & Mom care'), ('ND', 'Nutrition and drinks'), ('PC', 'Personal care'), ('OM', 'OTC Medicines'), ('PM', 'Prescription Medicines')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(upload_to='presimg')),
                ('newuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
