# Generated by Django 3.2.6 on 2022-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Comilla', 'Comilla'), ('Barishal', 'Barishal')], default='Dhaka', max_length=50),
        ),
    ]
