# Generated by Django 3.2.6 on 2022-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=40)),
                ('candidate_phone', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
            ],
        ),
    ]
