# Generated by Django 3.2.6 on 2022-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_bkashpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cattype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
