# Generated by Django 3.2.6 on 2022-05-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_newtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=40)),
                ('candidate_phone', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('prodcutview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediapp.product')),
            ],
        ),
    ]
