# Generated by Django 3.2.6 on 2022-05-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_bkashproductpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashproductpayment',
            name='prodcutview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediapp.cart'),
        ),
    ]
