# Generated by Django 3.2.6 on 2022-05-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0006_alter_bkashproductpayment_prodcutview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTable',
        ),
    ]
