# Generated by Django 3.2.6 on 2022-05-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0008_alter_bkashproductpayment_prodcutview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkashproductpayment',
            name='prodcutview',
        ),
    ]
