# Generated by Django 4.0.3 on 2022-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0009_remove_bkashproductpayment_prodcutview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulanceadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_phone', models.IntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Dhaka Metro', 'Dhaka Metro'), ('Dhaka Mirpur 10', 'Dhaka Mirpur 10'), ('Dhaka Gulshan', 'Dhaka Gulshan'), ('Dhaka Mirpur 12', 'Dhaka Mirpur 12'), ('Sylhet', 'Sylhet'), ('Kanaigat', 'Kanaigat'), ('Beanibazar', 'Beanibazar'), ('Golapgonj', 'Golapgonj'), ('Jkoigonj', 'Joigonj')], max_length=50)),
            ],
        ),
    ]
